export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const FETCH_RECIPES = 'FETCH_RECIPES';
export const SET_SEARCHED_RECIPES = 'SET_SEARCHED_RECIPES';

export const LISTADO = 'LISTADO';

export const LISTADO_USUARIO = 'LISTADO_USUARIO';

export const CREAR_RECETA = 'CREAR_RECETA';
export const ELIMINAR_RECETA = 'ELIMINAR_RECETA';
export const EDITAR_RECETA = 'EDITAR_RECETA';
